Learning-Fuze/c1218_movie_funder

- dummydata/comparables.js
- dummydata/comparables.json
- dummydata/currentconnections.js
- dummydata/currentconnections.json
- dummydata/datadump.sql
- dummydata/fundingpartners.js
- dummydata/fundingpartners.json
- dummydata/projects.js
- dummydata/projects.json
- dummydata/users.js
- dummydata/users.json
Added dummy data for the comparables table
Added dummy data for the current_connections table
Added dummy data for the funding_partners table
Added dummy data for the projects table
Added dummy data for the users table
Added sql dump for initial setup of database
> Added dummy data folder

- dummydata/comparables.js
- dummydata/comparables.json
- public/api/calculations.php
- public/api/comparables.php
- public/api/mysqlconnect.php
- public/api/projects.php
- public/api/test.php
got the data from the database                                                                                      
restructured the data to fit the dummy data                                                                         
checked the data built through postman                                                                              
also json encoded'
> Testing endpoint

- .gitignore
- config/mysqlconnect.php
- config/setup.php
- public/api/comparables.php
- public/api/projects.php
Added error handling to the comparables end point
Added basic projects endpoint
Added error handling to the projects endpoint
Added one setup file to handle errors throughout php
Updated gitignore file
> Added basic endpoint and error handling

- package-lock.json
- package.json
- src/actions/index.js
- src/components/aboutus/index.js
- src/components/aboutus/person.js
- src/components/app.js
- src/components/comparables/index.js
- src/components/contact/index.js
- src/components/financial/index.js
- src/components/home/index.js
- src/components/navbar/index.js
- src/components/newprojects/index.js
- src/index.js
- src/reducers/index.js
Setup Redux Folders 
-Set up routing
> Redux setup

- dummydata/datadump.sql
- dummydata/financials.js
- dummydata/financials.json
verified the json lint
did dump of the database
created the percentages table in the databse
calculated numbers based on spreadsheets
> added the dummy data for the financials endpoint

- public/api/financial.php
Added in various equations
Added in rounding for the ratio
Added in basic error handling
Added in success boolean
> Updated Financial Endpoint

- public/api/comparables.php
- public/api/projects.php
Added more psudo code for what needs to be built out on the endpoint
Added a more detailed query to get things started
Added error handling
Tested in Postman to make sure query was returning properly
> Updates to the Projects Endpoint

- dummydata/comparables.js
- dummydata/comparables.json
- public/api/comparables.php
verfied json lint
updated the query to grab the image url for the comparables
tested the data got back through postman
> updated the dummy data

- src/components/comparables/index.js
- src/components/home/index.js
- src/components/newprojects/index.js
- src/section/comparables.scss
added the functionality to the buttons
when the buttons are clicked they are routed to the correct page
> routing the buttons

- public/api/addproject.php
grabbed the comparables film titles
queried the databse to find the comparables ids
insert query to combine new project to the comparables film ids
updated the our out for the front end
> worked in the add project end point

- public/api/addproject.php
have error handling on the add project                                             
front end needs to sent us the requiring fields                                                    
runtime, logline,title,releasedyear,genre,mpaa,developmentStage,synopsis,film1, and film2          
if any of the above are sent an error will be thrown saying that the particular field is missing'
> Error proj

- src/components/newprojects/index.js
- src/section/newproject.scss
updated the runtime to say minutes in parenthesis and year so say select year
> updated runtime to display minutes and year

- src/components/home/index.js
- src/section/newproject.scss
Updated the title on the home page
Updated the paragraph on the home page
> Home Page Updates

- src/components/aboutus/index.js
- src/components/home/index.js
- src/section/newproject.scss
Updated the link to Diana's portfolio.
> Diana link

- public/api/financial.php
for the rounding used the floor method did not use round because when using php_round_half_down did not work to round the decimal with the floor method we round down to the nearest integer
checked in postman that the values where floored
> round financials calculations in the financials php file

- src/components/financial/index.js
Updated the defaultActiveKey to 'northAmerica'
> Make North America Active Again

- src/components/comparables/index.js
- src/section/comparables.scss
Removed the Arrow Icon and replaced it with a buttons
Added the buttons to the top of the window
Made sure buttons still work
> Added buttons to Comparables

- public/api/financial.php
> Added error handling if strings are passed to the database
> Added error handling if there are no params passed in
> Added error handling if there is only one param passed in
> Added error handling if there are no valid params found in the database
> Moved the data declaration to when we are using it to clean up code
> Make Financial Endpoint Dynamic

- src/components/contact/index.js
- src/components/helpers/forms.js
- src/components/test.js
- src/reducers/token_reducer.js
> deleted console log

- public/api/comparables.php
- public/api/financial.php
- public/api/sign_in.php
tested the query through phpmyAdmin to select the user id
gave output to frontend to say whether or not the user is loged in
did error handling for making sure that only one user should be coming back
created the sign in endpoint
build error handling to verify that data is coming in
build error handling for login email and valid
build error handling for making sure there is a password
password sha
trying to build out the query
> backend Sign in

- src/actions/index.js
- src/components/signin/index.js
- src/reducers/index.js
- src/reducers/signin_reducer.js
getting a repsonse of login of true
> made connection of frontend and back end for the sigin page

- src/components/contact/index.js
- src/components/signin/index.js
routed the user after they sigin in to the project page for now!
> routing to projects

- src/components/helpers/form/drop_down.js
- src/components/newprojects/index.js
- src/components/signin/index.js
- src/reducers/signin_reducer.js
- src/section/_main.scss
- src/section/newproject.scss
added conditional to stop submit button if production stage has a value of default
> project bug

- public/api/myprojects.php
myprojects basic endpoint is complete                                  
when hit the end point the frontend should be able to view the data like in           
the projects dummy data                                                               
did error checking so that if the user is not logged in then will say need to be logged in                                                                                    throw an error if the user has now projects
> My projects

- src/actions/index.js
- src/components/projects/index.js
- src/reducers/myprojects_reducer.js
updated state
created a build project function
mapped through projects and passed in build function
added some styling
> added initial action and reducer

- src/actions/index.js
- src/components/comparables/index.js
- src/components/financial/global.js
- src/components/financial/northAmerica.js
- src/components/financial/other.js
- src/components/navbar/index.js
- src/components/newprojects/index.js
- src/components/projects/index.js
- src/reducers/movie_reducer.js
- src/section/_main.scss
- src/section/aboutus.scss
- src/section/home.scss
- src/section/newproject.scss
- src/section/projects.scss
- src/section/terms.scss
- made page titles smaller and aligned with hamburger menu in mobile view
- added more detailed information to tooltips
- removed home link from navbar
- fixed button overflow in my projects
- aligned buttons when stacked over each other
- removed slashes from variable names in financial pages
> completed all changes in stage 1:

- public/api/signin.php
updated the object being sent to the front
> update sign-in endpoint

- dummydata/signin.js
- dummydata/signin.json
- public/api/signin.php
now sending an object that contains the project of the user as a key
for that key there is an array of objects and each object contains t
the key is associated with an array that contains objects
the objects have the id of the comparable film and the title
> updated the data being sent to the front end for the sigin end point

- dummydata/datadump.sql
- public/api/myprojects.php
- public/api/signin.php
- src/components/projects/index.js
did a data dump because some of the comparables were missing that needed to be added back in
storing the users projects into sessions and now my projects has access to them
> update the sessions
